import { createAction, props } from '@ngrx/store'
import { Starship } from '../../starship.model'
export const initStarships = createAction('[STARSHIPS] init')
export const storeStarships = createAction('[STARSHIPS] store starships', props<{ s: Starship[] }>())
export const throwStarships = createAction('[STARSHIPS] throw starships')
export const successGetStarships = createAction('[STARSHIPS] success get starships', props<{ s: Starship[], as: number }>())
export const errorGetStarships = createAction('[STARSHIPS] error get starships')
export const storeCurrentPage = createAction('[STARSHIPS] store current page', props<{ p: number }>())
export const throwCurrentPage = createAction('[STARSHIPS] throw current page')
export const storePlanetsAmount = createAction('[STARSHIPS] store pages', props<{ p: number }>())
export const throwPlanetsAmount = createAction('[STARSHIPS] throw pages')
export const storeStarship = createAction('[STARSHIPS] store starship', props<{ s: Starship }>())
export const throwStarship = createAction('[STARSHIPS] throw starship')
export const storeStarshipId = createAction('[STARSHIPS] store starship id', props<{ id: string }>())
export const throwStarshipId = createAction('[STARSHIPS] throw starship id')
export const successGetStarship = createAction('[STARSHIPS] success get starship', props<{ s: Starship }>())
export const errorGetStarship = createAction('[STARSHIPS] error get starship')
